name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run black
        run: poetry run black --check .
      - name: Run ruff
        run: poetry run ruff check .
      - name: Run tests
        run: poetry run pytest -q
